GET http://localhost:5057/games

###
GET http://localhost:5057/games/15

###
POST http://localhost:5057/games/
Content-Type: application/json

  {
    "id": 11,
    "name": "Killing Floor",
    "genreId": 6,
    "price": 5.99,
    "releaseDate": "2009-11-11"
  }

###
PUT http://localhost:5057/games/16
Content-Type: application/json

 {
    "id": 1,
    "name": "Street Fighter II Turbo",
    "genre": "Fighting",
    "price": 19.99,
    "releaseDate": "1992-07-15"
  }

###
DELETE http://localhost:5057/games/2